projet/app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from .views import (
	HomeView, 
	CheckoutView, 
	ProductDetail,
	add_to_cart,
	remove_from_cart,
	remove_single_from_cart,
	PaymentView,
	OrderSummaryView,
	payment_complete,
	DonorListView,
	DonorCreateView,
	DonorUpdateView,
	DonorDeleteView,
	OrderItemListView,
	#Dashboard,
	CustomerListView,
	CustomerDeleteView,
	DownloadPDF,
	ViewPDF,

	
	)



urlpatterns = [
	#path('', Dashboard.as_view(), name='home'),
    path('', HomeView.as_view(), name='home'),
    
    path('donor_list/', DonorListView.as_view(), name='donor_list'),
    path('new_donor/', DonorCreateView.as_view(), name= 'new_donor'),

    path('donor_update/<int:pk>/', DonorUpdateView.as_view(), name='donor_update'),
    path('donor_delete/<int:pk>/delete/', DonorDeleteView.as_view(), name='donor_delete' ),


    
    path('customer_list/', CustomerListView.as_view(), name='customer_list'),
    path('customer_delete/<int:pk>/delete/', CustomerDeleteView.as_view(), name='customer_delete' ),

    
    path('pdf_download/', DownloadPDF.as_view(), name="pdf_download"),
    path('pdf_view/',ViewPDF.as_view(), name="pdf_view"),

    path('order_list/', OrderItemListView.as_view(), name='order_list'),
    path('add-to-cart/<slug>/', add_to_cart, name='add_to_cart'),
    path('accounts/profile/' , TemplateView.as_view(template_name="home.html")),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove_from_cart'),
    path('remove-single-from-cart/<slug>/', remove_single_from_cart, name='remove_single_from_cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('product/<slug>/', ProductDetail.as_view(), name='product'),
    path('order-summary/', OrderSummaryView.as_view(), name='order_summary'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('payment-complete', payment_complete, name="payment_complete"),






]

projet/projet/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('app.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projet/app/models.py
from django.db import models
from django.contrib.auth.models import User
from django_countries.fields import CountryField
from django.shortcuts import reverse


CATEGORY_CHOICES = (
    ('B', 'Blood'),
    ('P', 'Plasma'),
    ('C', 'Cells')
)

PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'Paypal'),
)

class Item(models.Model):
    title = models.CharField(max_length=200)
    price = models.IntegerField()
    discount_price = models.IntegerField(blank=True, null=True)
    slug = models.SlugField()
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    

    def __str__(self):
        return self.title

    def get_add_to_cart_url(self):
        return reverse('add_to_cart', kwargs={'slug': self.slug})

    def get_remove_from_cart_url(self):
        return reverse('remove_from_cart', kwargs={'slug': self.slug})

    def get_remove_single_from_cart_url(self):
        return reverse('remove_single_from_cart', kwargs={'slug': self.slug})





class OrderItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_item_discount_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_final_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_item_discount_price()
        return self.get_total_item_price()

    

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    address = models.ForeignKey("Address", on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey("Payment", on_delete=models.SET_NULL, blank=True, null=True)
    ordered = models.BooleanField(default=False)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total


class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    street_address = models.CharField(max_length=200)
    apartment_address = models.CharField(max_length=200)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=200)
    save_info = models.BooleanField(default=False)
    default = models.BooleanField(default=False)
    use_default = models.BooleanField(default=False)
    payment_option = models.CharField(choices=PAYMENT_CHOICES, max_length=2)

    class Meta:
        verbose_name_plural = 'Addresses'

    def __str__(self):
        return self.user.username


class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    stripe_charge_id = models.CharField(max_length=100)
    amount = models.CharField(max_length=100)

    def __str__(self):
        return self.user.username



class Donor(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    blood_group = models.ForeignKey(Item, on_delete = models.CASCADE)
    phone = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

    def __str__(self):
        return self.name

projet/templates/base.html
{% load static %}
{% load cart_template_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
  <script src="https://code.highcharts.com/highcharts.src.js"></script>
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}{% endblock title %}| Blood Bank</title>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    .dropbtn {
  background-color: white;
  color: black;
  padding: 16px;
  font-size: 16px;
  border: none;
}

.dropdown {
  position: relative;
  display: inline-block;
}

.dropdown-content {
  display: none;
  position: absolute;
  background-color: #f1f1f1;
  min-width: 160px;
  color :black;
  z-index: 1;
}

.dropdown-content a {
  color: black;
  padding: 12px 16px;
  text-decoration: none;
  display: block;
}

.dropdown-content a:hover {background-color: #ddd;}

.dropdown:hover .dropdown-content {display: block;}

.dropdown:hover .dropbtn {background-color: white;}

  </style>
</head>
<body>

<nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar" style="width: 1108px;margin-left: 284px;margin-top: 23px;">
<div class="container">
  <img  src="https://rgims.ac.in/wp-content/uploads/2016/12/blood-bank.jpg" alt="" style="width: 75px;margin-left: auto;">
    <a class="navbar-brand waves-effect" href="{% url 'home' %}">
    <strong class="red-text">Blood Bank</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ">
        <li class="nav-item">
        <a class="nav-link waves-effect" href="{% url 'home' %}"> <b>Home</b>
        </a>
        </li>
        
    </ul>
    {% if request.user.is_staff %}

    <ul class="navbar-nav ">
        <li class="nav-item">
        <a class="nav-link waves-effect" href="{% url 'customer_list' %}"><b>Customers</b>
        </a>
        </li>
        
    </ul>

      <ul class="navbar-nav ">
        <li class="nav-item">
        <a class="nav-link waves-effect" href="{% url 'order_list' %}"><b>Orders</b>
        </a>
        </li>
        
    </ul>

    <div class="dropdown">
  <button class="dropbtn">Donor</button>
  <div class="dropdown-content">
    <a href="{% url 'new_donor' %}">Add donor </a>
    <a href="{% url 'donor_list' %}">Donor list</a>
    
  </div>
  </div>
     
    {% endif %}
      
         <div class="dropdown mr-auto">
  <button class="dropbtn"></button>
  <div class="dropdown-content">
  
    
  </div>
  </div>
    <ul class="navbar-nav nav-flex-icons">
      {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="#">Hello, {{request.user.username}}
          </a>
        </li>
        <li class="nav-item">
        <a href="{% url 'order_summary' %}" class="nav-link waves-effect">
            <span class="badge red z-depth-1 mr-1">{{ request.user|cart_item_count}}</span>
            <i class="fas fa-shopping-cart"></i>
            <span class="clearfix d-none d-sm-inline-block"> Cart </span>
        </a>
        </li>
        
         <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_logout' %}">Logout
          </a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_login' %}">Login
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link waves-effect" href="{% url 'account_signup' %}">Signup
          </a>
        </li>
      {% endif %}

    </ul>

    </div>

</div>
</nav>

<div class="container" style="margin-top:15px;">
  {% if messages %}
    {% for message in messages %}
      <div style="margin-top:7rem;" class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" s>
        {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    {% endfor %}
  {% endif %}
</div>


{% block content %}
  
{% endblock content %}


<footer class="page-footer text-center font-small mt-4 wow fadeIn" style="width: 1118px;margin-left: 283px;">


<!--/.Call to action-->



<!--Copyright-->
<div class="footer-copyright py-3 bg-danger red lighten-2">
    © 2019 Copyright:
    <a href="" target="_blank"> bloodbank.com </a>
</div>
<!--/.Copyright-->

</footer>


  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
  <script type="text/javascript">
    new WOW().init();

  </script>

</body>

</html>

projet/templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}checkout{% endblock title %}

{% block content %}

<main class="mt-5 pt-4">
  <div class="container wow fadeIn">
    <h2 class="my-5 h2 text-center">Checkout form</h2>
    <div class="row">
      <div class="col-md-8 mb-4" style="margin-left: 191px;">
        <div class="card">
<!-- 
          <form action="" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-info">Submit</button>
          </form> -->


          <form class="card-body" method="POST">
            {% csrf_token %}
            <div class="md-form mb-5">
              <input type="text" name="street_address" id="street_address" class="form-control" placeholder="" required>
              <label for="street_address" class="">Street address</label>
            </div>
            <div class="md-form mb-5">
              <input type="text" name="apartment_address" id="apartment_address" class="form-control" placeholder="" required>
              <label for="apartment_address" class="">Apartment address</label>
            </div>

            <div class="row">
              <div class="col-lg-4 col-md-12 mb-4"> 
                <label for="country">Country</label>
                {{form.country}}
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>
              </div>
              <div class="col-lg-4 col-md-6 mb-4">
                <label for="zip">Zip</label>
                <input type="text" name="zip" class="form-control" id="zip" placeholder="Zipcode..." >
                <div class="invalid-feedback">
                  Zip code required.
                </div>
              </div>
            </div>
            <hr>
           <div class="custom-control custom-checkbox">
              <input type="checkbox" name="save_info" class="custom-control-input" id="save_info">
              <label class="custom-control-label" for="save_info">Save as default address</label>
            </div>
            <div class="custom-control custom-checkbox">
              <input type="checkbox" name="use_default" class="custom-control-input" id="use_default">
              <label class="custom-control-label" for="use_default">Use default address : {{address.street_address}}, {{address.apartment_address}}, {{address.country}}</label>
            </div>
            <hr> 
           
            
              <div class="custom-control custom-radio">
                <input id="paypal" value="P" name="payment_option" type="radio" class="custom-control-input">
                <label class="custom-control-label" for="paypal">Pay</label>
              </div>
               
            <hr class="mb-4">
            <button class="btn btn-danger btn-lg btn-block" type="submit">Continue to Payment</button>
          </form>
        </div>
      </div>
      <!--Grid column-->

      <!--Grid column-->
      <div class="col-md-4 mb-4">
        
      </div>
    </div>
  </div>
</main> 

{% endblock content %}

projet/templates/confirm_delete.html
{% extends 'base.html' %}

{% block title %}delete{% endblock title %}
{% block content %}

<main class="mt-5 pt-4">
  <div class="container">
    <section class=" mb-4 col-6 col-md-6 offset-3" style="box-shadow: 1px 5px 14px 0px gray; border-radius: 5px;margin-top: 67px;">

	<form method="post">
		{% csrf_token %}
    <p style="margin-left: 46px;font-size: medium; font-weight: 600;" class="text-center">Are you sure you want to delete "{{ object }}"?</p>


     <button type="submit" class="btn btn-success text-center" style=" margin-left: 206px;margin-top: 41px;box-shadow: 2px 3px black;">
       	<i class="fa fa-check-square-o" aria-hidden="true">yes</i>
       </button>
</form>

</section>
  </div>
</main>
                
{% endblock content %}

projet/templates/customer.html
{% extends 'base.html' %}
{% block title %}Customers{% endblock title %}
{% block content %}

<style>
  .small-img{
    width: 70px;
    height: 70px;
  }
</style>
<main class="mt-5 pt-4">
  <div class="container"  style="margin-top: 37px;">
    <section class="mb-4">
    

      <h1 class="text-center">user</h1>
      <div class="table-responsive text-nowrap">
        
        <table class="table">
          <thead class="bg-danger red lighten-3 text-white">
            <tr>
              
              <th scope="col">Username</th>
              
              <th scope="col">Email</th>
            </tr>
          </thead>
           <tbody>
                                    {% for user in object_list %}
                                        <tr class="gradeX">
                                            <td>{{ user.username }}</td>
                                           

                                            <td>{{ user.email }}</td>


                                            <td>
                                               
                                               <a href="{% url 'customer_delete' user.id %}">
                                <span style="color: red;" class="float-right">
                                    <i class="fas fa-trash-alt"></i>
                                </span>
                                              </a>
                                        
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
        </table>
        

      </div>
    </section>
  </div>
</main>

{% endblock content %}

projet/templates/donor_list.html
{% extends "base.html" %} 
{% block title %}donor list{% endblock title %}
{% block content %}
<style>
  .small-img{
    width: 70px;
    height: 70px;
  }
</style>
<main class="mt-5 pt-4">
  <div class="container"  style="margin-top: 37px;">
    <section class="mb-4">
    

      <h1 class="text-center">Donor</h1>
      <div class="table-responsive text-nowrap">
        
        <table class="table">
          <thead class="bg-danger red lighten-3 text-white">
            <tr>
              
              <th scope="col">Name</th>
              <th scope="col">Age</th>
              <th scope="col">Blood type</th>
              <th scope="col">Phone</th>
              <th scope="col">Address</th>
            </tr>
          </thead>
           <tbody>
                                    {% for donor in object_list %}
                                        <tr class="gradeX">
                                            <td>{{ donor.name }}</td>
                                            <td>{{ donor.age }}</td>
                                            <td>{{ donor.blood_group }}</td>
                                            <td>{{ donor.phone }}</td>

                                            <td>{{ donor.address }}</td>


                                            <td>
                                                <a href="{% url 'donor_update' donor.id %}">
                              <span style="color: green;" class="float-right" >
                                    <i class="fas fa-edit" style="margin-left: 50px;"></i>
                             </span>
                                             </a>
                                               <a href="{% url 'donor_delete' donor.id %}">
                                <span style="color: red;" class="float-right">
                                    <i class="fas fa-trash-alt"></i>
                                </span>
                                              </a>
                                        
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
        </table>
        

      </div>
    </section>
  </div>
</main>
{% endblock content %}

projet/templates/home.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% block content %}
{% if request.user.is_staff %}
<div class="col-xl-3 col-md-6 mb-4 " style="width: 221px;margin-top: 134px;
margin-left: 271px;">
                <div class="card border-left-primary shadow h-100 py-2">
                  <div class="card-body">
                    <div class="row no-gutters align-items-center">
                      <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Donors</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">{{total_donors}}</div>
                      </div>
                      <div class="col-auto">
                        <i class="fas fa-handshake fa-2x text-gray-300"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col-xl-3 col-md-6 mb-4" style="width: 221px;margin-left: 565px;margin-top: -134px;">
                  <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                      <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                          <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Customers</div>
                          <div class="h5 mb-0 font-weight-bold text-gray-800">{{total_customers}}</div>
                        </div>
                        <div class="col-auto">
                          <i class="fa fa-users fa-2x text-gray-300"></i>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              <div class="col-xl-3 col-md-6 mb-4" style="width: 221px;margin-top: -137px;margin-left: 878px;">
                  <div class="card border-left-primary shadow h-100 py-2">
                    <div class="card-body">
                      <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                          <div class="text-xs font-weight-bold text-danger text-uppercase mb-1">Orders</div>
                          <div class="h5 mb-0 font-weight-bold text-gray-800">{{total_orders}}</div>
                        </div>
                        <div class="col-auto">
                          <i class="fa fa-truck fa-2x text-gray-300"></i>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
  
              <!-- Contact Card Example -->
              <div class="col-xl-3 col-md-6 mb-4" style="width: 221px;margin-top: -133px;margin-left: 1192px;">
                <div class="card border-left-warning shadow h-100 py-2">
                  <div class="card-body">
                    <div class="row no-gutters align-items-center">
                      <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Contact</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800">75972708</div>
                      </div>
                      <div class="col-auto">
                        <i class="fas fa-comments fa-2x text-gray-300"></i>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
{% endif %}
<div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

  <!--Indicators-->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-1z" data-slide-to="1"></li>
    <li data-target="#carousel-example-1z" data-slide-to="2"></li>
  </ol>
  <!--/.Indicators-->

  <!--Slides-->
  


<main style="margin-top: 99px;">
  <div class="container">
  


    <section class="text-center mb-4">
      <div class="row wow fadeIn">

        {% for object in object_list %}
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
            <div class="view overlay">
              
              <a href="{% url 'product' object.slug %}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <div class="card-body text-center">
              <a href="" class="grey-text">
                <h9>{{object.get_category_display}}</h9>
              </a>
              <h5>
                <strong>
                  <a href="{% url 'product' object.slug %}" class="dark-grey-text">{{object.title}}
                    
                  </a>
                </strong>
              </h5>
              <h8 class="font-weight-bold red-text">
                {% if object.discount_price %}
                <strong>BIF {{object.discount_price}}</strong>
                {% else %}
                  <strong>BIF {{object.price}}</strong>
                {% endif %}
              </h8>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        <!--Arrow left-->
        <li class="page-item disabled">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>

        <li class="page-item active">
          <a class="page-link" href="#">1
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">4</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">5</a>
        </li>

        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>
    </nav>
    <!--Pagination-->

  </div>
</main>
{% endblock content %}

  

  

projet/templates/invoice.html
  <head>
<style>
    @page {
        size: a4 portrait;
        @frame header_frame {           /* Static Frame */
            -pdf-frame-content: header_content;
            left: 50pt; width: 512pt; top: 50pt; height: 40pt;
        }
        @frame content_frame {          /* Content Frame */
            left: 50pt; width: 512pt; top: 90pt; height: 632pt;
        }
        @frame footer_frame {           /* Another static Frame */
            -pdf-frame-content: footer_content;
            left: 50pt; width: 512pt; top: 772pt; height: 20pt;
        }
    }
</style>
</head>

<body>
    <!-- Content for Static Frame 'header_frame' -->
    <div id="header_content">
    	<h3>Blood Bank Company</h3>
    </div>

    <!-- Content for Static Frame 'footer_frame' -->
    <div id="footer_content">(c) - page <pdf:pagenumber>
        of <pdf:pagecount>
    </div>

    <!-- HTML Content -->
    <table>
    		<tr>
    			<td>{{address}}</td>
    			<td>{{phone}}</td>
    		</tr>
    		<tr>
    			<td>{{city}} {{state}},</td>
    			<td>{{email}}</td>
    		</tr>
    		<tr>
    			<td>{{zipcode}}</td>
    			<td>{{website}}</td>
    		</tr>
    </table>

    <hr>

     <table class="table">
          <thead class="bg-danger red lighten-3 text-white">
            <tr>
              
              <th scope="col">Item title</th>
              <th scope="col">Quantity</th>
              <th scope="col">Price</th>
              <th scope="col">Total Item Price</th>
            </tr>

          </thead>

          <tbody >

            {% for order_item in order_item %}
              <tr>
              
              <td style="margin-left: 80px;">{{order_item.item.title}}</td>
              <td style="margin-left: 80px;"> 
               
                {{order_item.quantity}}
                
              </td>
             
                <td style="margin-left: 80px;">{{order_item.item.price}}</td>
              
              <td style="margin-left: 80px;">{{order_item.get_final_price}}
                
              
              </td>
            </tr>
           
            {% endfor %}
          
          </tbody>
        </table>

    
</body>

projet/templates/new_donor.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}Add donor {% endblock title %}

{% block content %}

 <main class="mt-5 pt-4">
  <div class="container">
    <section class=" mb-4 col-6 col-md-6 offset-3" style="box-shadow: 1px 5px 14px 0px gray; border-radius: 5px;margin-top: 89px;">
<h3 class="text-center">Add Donor</h3>

      <form  method="POST" action="{% url 'new_donor' %}" style="width: 300px;margin-left: 108px;">
        {% csrf_token %}
        {{ form|crispy }}
        
        
        <button class="btn btn-danger  rounded" type="submit">Save</button>
        
      </form>

    </section>
  </div>
</main>

{% endblock content %}

projet/templates/product.html
{% extends 'base.html' %}
{% block title %}Product{% endblock title %}

{% block content %}

<main class="mt-5 pt-4">
  <div class="container dark-grey-text mt-5" style="margin-right: 1843px;">
    <div class="row wow fadeIn">
      <div class="col-md-6 mb-4">
        
      </div>
      <div class="col-md-6 mb-4">
        <div class="p-4">
          <div class="mb-3">
            <a href="">
              <span class="badge purple mr-1">{{object.get_category_display}}</span>
            </a>
          <h4 class="mt-3"><strong>{{object.title}}</strong></h4>
          <p class="lead">
            <span class="mr-1">
              {% if object.discount_price %}
                <del>BIF{{object.price}}</del>
                <span>BIF{{object.discount_price}}</span>
              {% else %}
                <span>BIF{{object.price}}</span>
              {% endif %}
            </span>
          </p>
          </div>
          
          

            <a href="{{object.get_add_to_cart_url}}" class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
            <i class="fas fa-shopping-cart ml-1"></i>
          </a>
          <a href="{{object.get_remove_from_cart_url}}" class="btn btn-danger btn-md my-0 p" type="submit">Remove from cart
            <i class="fas fa-shopping-cart ml-1"></i>
          </a>

        </div>
      </div>
    </div>
    <hr>
   
   
  </div>
</main>

{% endblock content %}
  
 